### PR TITLE
Bump current mypy version to 0.800

### PR DESCRIPTION
**Pull request by person142**
Mypy prior to 0.800 didn't support Python 3.9, so I was getting test
failures locally. Bumped the version in `current_mypy_version.txt` to
fix that. New mypy was also unhappy about `test/types` being a
top-level module (since it shadows the stdlib types module); dealt
with that by adding an `__init__` to test.

### CODE REVIEW

**Comment by person142** [comment]
Ach I only just saw https://github.com/dshahbaz/bazel-mypy-integration/wiki#2-confusion-around-py_library-targets-with-imports. So I guess it's between a rock and a hard place.

**Comment by thundergolfer** [comment]
> Ach I only just saw ...

I hadn't seen that wiki before. Looks pretty useful.

**Comment by thundergolfer** [comment]
If we were going to update the version, the README reference to a mypy version should also be updated 👍

**Comment by person142** [comment]
> the README reference to a mypy version should also be updated

Done in https://github.com/thundergolfer/bazel-mypy-integration/pull/37/commits/87089096631fafa46f221ed4cca90218906496f9.

Feel free to reject-I can work around the 3.9 issue.

**Comment by thundergolfer** [comment]
Is the "the 3.9 issue" what's detailed in https://github.com/dshahbaz/bazel-mypy-integration/wiki#2-confusion-around-py_library-targets-with-imports ?

**Comment by person142** [comment]
> Is the "the 3.9 issue"

Yeah, you need 0.800 to support 3.9 (ref https://mypy-lang.blogspot.com/2021/01/mypy-0800-released.html), but then that issue kicks in.

**Comment by alexeagle** [comment]
Since #98 it's up to users to bring the version of mypy, so this is no longer a job of this ruleset.

**Pull request closed without merging**
